default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  database: shogi_app_development

test:
  <<: *default
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  database: shogi_app_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: shogi_app_production
  username: <%= ENV.fetch('DB_USERNAME', 'shogi_app') %>
  password: <%= ENV.fetch('DB_PASSWORD', ENV['SHOGIAPP_DATABASE_PASSWORD']) %>