services: 
  db: 
    image: postgres:14
    volumes: 
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shogi_app_development
    ports:
      - "5432:5432"
  backend: 
    build: ./backend
    entrypoint: ["bash", "/app/entrypoint.sh"]
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"]
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/shogi_app_development
    tty: true
    stdin_open: true
  frontend:
    build: ./frontend
    command: ["sh", "/app/start.sh"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./backend/swagger:/app/backend/swagger
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  db-data: