name: Rails RSpec Tests

on:
  workflow_dispatch:  # 手動実行トリガー
  push:
    paths-ignore:
      - 'frontend/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'frontend/**'
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 全履歴をフェッチして正確なコミット情報を取得

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 現在の GitHub Actions 環境では直接 docker-compose コマンドが使えるバージョンもあります
    - name: Set up Docker Compose
      run: |
        # 現在のDockerとDocker Composeのバージョンを確認
        docker --version
        docker compose version || echo "Docker Compose V2 not available"
        
        # Docker Compose V2が利用できない場合はインストール
        if ! command -v docker-compose &> /dev/null; then
          echo "Installing Docker Compose V1..."
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        fi

    - name: Build and run tests with docker-compose
      run: |
        # Dockerイメージをビルド
        docker-compose build
        
        # データベースをセットアップ
        docker-compose run --rm backend bin/rails db:create db:schema:load
        
        # テストを実行
        docker-compose run --rm -e RAILS_ENV=test backend bundle exec rspec 