name: Rails RSpec Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - '.github/workflows/rspec.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - '.github/workflows/rspec.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run tests with docker-compose
      run: |
        docker-compose build
        docker-compose run --rm backend bin/rails db:create db:schema:load
        docker-compose run --rm -e RAILS_ENV=test backend bundle exec rspec 